//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaWuClub.Web.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClubEntities : DbContext
    {
        public ClubEntities()
            : base("name=ClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<ArticleReview> ArticleReviews { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleTag> ArticleTags { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<View> Views { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<ViewQuestion> ViewQuestions { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ViewActivity> ViewActivities { get; set; }
        public virtual DbSet<ViewAnswer> ViewAnswers { get; set; }
        public virtual DbSet<ActivityOrder> ActivityOrders { get; set; }
        public virtual DbSet<ViewArticleReview> ViewArticleReviews { get; set; }
        public virtual DbSet<SystemArticle> SystemArticles { get; set; }
        public virtual DbSet<AnswerVote> AnswerVotes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<BannerType> BannerTypes { get; set; }
        public virtual DbSet<ViewBanner> ViewBanners { get; set; }
        public virtual DbSet<TagMap> TagMaps { get; set; }
        public virtual DbSet<TopicCategory> TopicCategories { get; set; }
        public virtual DbSet<TopicReview> TopicReviews { get; set; }
        public virtual DbSet<ViewTopicCategory> ViewTopicCategories { get; set; }
        public virtual DbSet<AdminAccount> AdminAccounts { get; set; }
        public virtual DbSet<AdminType> AdminTypes { get; set; }
        public virtual DbSet<TopicIndex> TopicIndexes { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TopicActivity> TopicActivities { get; set; }
        public virtual DbSet<TopicTask> TopicTasks { get; set; }
        public virtual DbSet<ViewTopicActivity> ViewTopicActivities { get; set; }
        public virtual DbSet<ViewTopicTask> ViewTopicTasks { get; set; }
        public virtual DbSet<ViewTopicIndex> ViewTopicIndexes { get; set; }
        public virtual DbSet<ViewTopic> ViewTopics { get; set; }
        public virtual DbSet<ViewTopicReview> ViewTopicReviews { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<ViewArticle> ViewArticles { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<VideoReview> VideoReviews { get; set; }
        public virtual DbSet<ViewVideoReview> ViewVideoReviews { get; set; }
        public virtual DbSet<ViewDocument> ViewDocuments { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<TopicInvolved> TopicInvolveds { get; set; }
        public virtual DbSet<ViewTopicInvolved> ViewTopicInvolveds { get; set; }
    }
}
