//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaWuClub.Web.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public int UserId { get; set; }
        public string Tags { get; set; }
        public string TagsId { get; set; }
        public byte Type { get; set; }
        public int Views { get; set; }
        public int Downs { get; set; }
        public int Status { get; set; }
        public System.DateTime VarDate { get; set; }
    }
}
