//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaWuClub.Web.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagMap
    {
        public int Id { get; set; }
        public string TagIds { get; set; }
        public string TagNames { get; set; }
        public int AId { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> VarDate { get; set; }
    }
}
