//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaWuClub.Web.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Intro { get; set; }
        public string Cover { get; set; }
        public int Credit { get; set; }
        public byte Actived { get; set; }
        public byte Role { get; set; }
        public byte Status { get; set; }
        public string ActivedCode { get; set; }
        public Nullable<byte> Membership { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<byte> Type { get; set; }
        public string Tid { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string LastLoginIP { get; set; }
    }
}
