//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaWuClub.Web.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTopicTask
    {
        public string NickName { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
        public int UserId { get; set; }
        public int Type { get; set; }
        public int Category { get; set; }
        public int Views { get; set; }
        public int Support { get; set; }
        public int Oppose { get; set; }
        public byte Status { get; set; }
        public int Area { get; set; }
        public int Likes { get; set; }
        public System.DateTime VarDate { get; set; }
        public string Cover { get; set; }
        public string Context { get; set; }
    }
}
