//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaWuClub.Web.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewActivity
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Cover { get; set; }
        public string Context { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Sponsor { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Cost { get; set; }
        public string Limited { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> VarDate { get; set; }
        public string Name { get; set; }
        public int AId { get; set; }
        public byte Node { get; set; }
    }
}
