//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaWuClub.Web.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAnswer
    {
        public int Id { get; set; }
        public int QId { get; set; }
        public int UserId { get; set; }
        public string Answer { get; set; }
        public int Agree { get; set; }
        public int Oppose { get; set; }
        public System.DateTime AnswerVarDate { get; set; }
        public int UId { get; set; }
        public string NickName { get; set; }
        public string Cover { get; set; }
        public string Intro { get; set; }
        public string RealName { get; set; }
        public string QuestionTitle { get; set; }
        public int QuestionId { get; set; }
    }
}
