//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaWuClub.Web.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewVideoReview
    {
        public int UId { get; set; }
        public int Id { get; set; }
        public int UserId { get; set; }
        public int VideoId { get; set; }
        public string Review { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> VarDate { get; set; }
        public string NickName { get; set; }
        public string Cover { get; set; }
    }
}
